package Vista;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Utils.ColorCelda;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Annia Benítez
 */
public class tablas extends javax.swing.JPanel {

    /**
     * Creates new form tablas
     */
    public tablas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tiempoPEspera = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tiempoPRespuesta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaParaAlgoritmo = new ColorCelda();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Tiempo promedio de espera:");

        tiempoPEspera.setText("0");
        tiempoPEspera.setEnabled(false);
        tiempoPEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoPEsperaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tiempo promedio de respuesta:");

        tiempoPRespuesta.setText("0");
        tiempoPRespuesta.setEnabled(false);

        tablaParaAlgoritmo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaParaAlgoritmo.setAutoResizeMode(0);
        jScrollPane1.setViewportView(tablaParaAlgoritmo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tiempoPEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tiempoPRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(804, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tiempoPEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tiempoPRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tiempoPEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoPEsperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoPEsperaActionPerformed

    public void cargarDatosEjercicio(String[][] tabla, String[] titulo, double espera, double respuesta) {
        DefaultTableModel model = (DefaultTableModel) tablaParaAlgoritmo.getModel();

        // Limpiar la tabla antes de cargar nuevos datos
        model.setRowCount(0);

        // Establecer los nombres de las columnas
        model.setColumnIdentifiers(titulo);
        
        //Muestra calculos resultados
        tiempoPEspera.setText(String.valueOf(espera));
        tiempoPRespuesta.setText(String.valueOf(respuesta));

        // Agregar cada celda de la matriz a la tabla, una por una
        for (String[] fila : tabla) {
            model.addRow(fila);
        }

        TableColumnModel columnModel = tablaParaAlgoritmo.getColumnModel();

        // Establece el ancho fijo para cada columna (por ejemplo, 100 píxeles)
        for (int columnIndex = 0; columnIndex < columnModel.getColumnCount(); columnIndex++) {
            TableColumn column = columnModel.getColumn(columnIndex);
            column.setPreferredWidth(35); // Establece el ancho deseado en píxeles
        }

    }

    public JTable getTablaParaAlgoritmo() {
        return tablaParaAlgoritmo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaParaAlgoritmo;
    public javax.swing.JTextField tiempoPEspera;
    public javax.swing.JTextField tiempoPRespuesta;
    // End of variables declaration//GEN-END:variables
}
